apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
      # - ./infra/k8s/ingress-srv.yaml
      # - ./infra/k8s/nats-depl.yaml
      # - ./infra/k8s/orders-depl.yaml
      # - ./infra/k8s/orders-mongo-depl.yaml
      # - ./infra/k8s/tickets-depl.yaml
      # - ./infra/k8s/tickets-mongo-depl.yaml
      # - ./infra/k8s/expiration-depl.yaml
      # - ./infra/k8s/expiration-redis-depl.yaml

      # - ./infra/k8s/payments-depl.yaml
      # - ./infra/k8s/payments-mongo-depl.yaml

      # - ./infra/k8s/auth-depl.yaml
      # - ./infra/k8s/auth-mongo-depl.yaml
build:
  artifacts:
    - image: imnotsmarttt/ticket-client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: .
    - image: imnotsmarttt/ticket-auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: imnotsmarttt/ticket-tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: imnotsmarttt/ticket-orders
      context: orders
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: imnotsmarttt/ticket-expiration
      context: expiration
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: imnotsmarttt/ticket-payments
      context: payments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    
